//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klada_v3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalcOddsTable
    {
        public CalcOddsTable(int eventID, string home, string away, string eventTime, decimal? odd1, string klada1, decimal? oddX, string kladaX, decimal? odd2, string klada2, decimal? odd1X, string klada1X, decimal? oddX2, string kladaX2, decimal? odd12, string klada12)
        {
            EventID = eventID;
            Home = home;
            Away = away;
            EventTime = eventTime;
            Odd1 = odd1;
            Klada1 = klada1;
            OddX = oddX;
            KladaX = kladaX;
            Odd2 = odd2;
            Klada2 = klada2;
            Odd1X = odd1X;
            Klada1X = klada1X;
            OddX2 = oddX2;
            KladaX2 = kladaX2;
            Odd12 = odd12;
            Klada12 = klada12;
        }

        public CalcOddsTable(int eventID, string home, string away, string eventTime, decimal? odd1, string klada1, decimal? oddX, string kladaX, decimal? odd2, string klada2, decimal? odd1X, string klada1X, decimal? oddX2, string kladaX2, decimal? odd12, string klada12, decimal? calcOdd, string sportType, int? sportTypeID)
        {
            EventID = eventID;
            Home = home;
            Away = away;
            EventTime = eventTime;
            Odd1 = odd1;
            Klada1 = klada1;
            OddX = oddX;
            KladaX = kladaX;
            Odd2 = odd2;
            Klada2 = klada2;
            Odd1X = odd1X;
            Klada1X = klada1X;
            OddX2 = oddX2;
            KladaX2 = kladaX2;
            Odd12 = odd12;
            Klada12 = klada12;
            CalcOdd = calcOdd;
            SportType = sportType;
            SportTypeID = sportTypeID;
        }

        public int EventID { get; set; }
        public string Home { get; set; }
        public string Away { get; set; }
        public string EventTime { get; set; }
        public Nullable<decimal> Odd1 { get; set; }
        public string Klada1 { get; set; }
        public Nullable<decimal> OddX { get; set; }
        public string KladaX { get; set; }
        public Nullable<decimal> Odd2 { get; set; }
        public string Klada2 { get; set; }
        public Nullable<decimal> Odd1X { get; set; }
        public string Klada1X { get; set; }
        public Nullable<decimal> OddX2 { get; set; }
        public string KladaX2 { get; set; }
        public Nullable<decimal> Odd12 { get; set; }
        public string Klada12 { get; set; }
        public Nullable<decimal> CalcOdd { get; set; }
        public string SportType { get; set; }
        public Nullable<int> SportTypeID { get; set; }
    }
}
