//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klada_v1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OddsTable
    {
        public int KladaID { get; set; }
        public string Home { get; set; }
        public string Away { get; set; }
        public string EventTime { get; set; }
        public string EventLink { get; set; }
        public Nullable<decimal> Odd1 { get; set; }
        public Nullable<decimal> OddX { get; set; }
        public Nullable<decimal> Odd2 { get; set; }
        public Nullable<decimal> Odd1X { get; set; }
        public Nullable<decimal> OddX2 { get; set; }
        public Nullable<decimal> Odd12 { get; set; }
        public Nullable<decimal> OddF2 { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<bool> InPlay { get; set; }
        public string KladaName { get; set; }
        public string SportType { get; set; }
        public Nullable<int> SportTypeID { get; set; }
    }
}
