//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klada_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRKladeEntities : DbContext
    {
        public HRKladeEntities()
            : base("name=HRKladeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CalcOddsTable> CalcOddsTables { get; set; }
        public virtual DbSet<MatchSystemID> MatchSystemIDs { get; set; }
        public virtual DbSet<OddsTable> OddsTables { get; set; }
    }
}
